<?php

namespace ContainerMl90l4b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMyClass1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\MyClass1' shared autowired service.
     *
     * @return \App\Controller\MyClass1
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/MyClass1.php';

        $container->services['App\\Controller\\MyClass1'] = $instance = new \App\Controller\MyClass1();

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\MyClass1', $container));

        return $instance;
    }
}
