#index:
#    path: /
#    controller: App\Controller\MyClass::index

index:
    path: /
    controller: App\Controller\MyClass::index


dev:
    path: /dev
    controller: App\Controller\MyClassDev::hello
