<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCSpQd6d\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCSpQd6d/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCSpQd6d.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCSpQd6d\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCSpQd6d\App_KernelDevDebugContainer([
    'container.build_hash' => 'CSpQd6d',
    'container.build_id' => 'aa3dd63f',
    'container.build_time' => 1639939017,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCSpQd6d');
